# Generated by Django 4.1 on 2022-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=5, null=True)),
                ('src', models.CharField(max_length=25, null=True)),
                ('dst', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_hosts', models.CharField(max_length=30, null=True)),
                ('destination_hosts', models.CharField(max_length=30, null=True)),
                ('tor_nodes', models.CharField(max_length=20, null=True)),
                ('possible_tor_traffic', models.CharField(max_length=20, null=True)),
                ('possible_malicious_traffic', models.CharField(max_length=20, null=True)),
                ('signatures', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, null=True)),
                ('ethernet', models.CharField(max_length=75, null=True)),
                ('forward', models.TextField(null=True)),
                ('reverse', models.TextField(null=True)),
                ('covert', models.CharField(max_length=10)),
                ('file_signatures', models.CharField(max_length=255, null=True)),
                ('ether_src', models.CharField(max_length=20, null=True)),
                ('ether_dst', models.CharField(max_length=20, null=True)),
                ('ip_src', models.CharField(max_length=20, null=True)),
                ('ip_dst', models.CharField(max_length=20, null=True)),
                ('ip', models.CharField(max_length=7, null=True)),
                ('protocol', models.CharField(max_length=10, null=True)),
                ('packet_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
