# Generated by Django 4.1 on 2022-08-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host',
            new_name='Hosts',
        ),
    ]
