# Generated by Django 4.1 on 2022-08-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0003_hostp_delete_hosts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostp',
            new_name='Host',
        ),
    ]
