# Generated by Django 4.1 on 2022-08-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0004_rename_hostp_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='op',
        ),
    ]
