# Generated by Django 4.1 on 2022-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0005_remove_host_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ip_protocol',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
