# Generated by Django 4.1 on 2022-08-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0006_host_ip_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='ip_protocol',
            new_name='ip_version',
        ),
    ]
