# Generated by Django 4.1 on 2022-08-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0007_rename_ip_protocol_host_ip_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='ip',
            new_name='ip_version',
        ),
        migrations.AddField(
            model_name='packet',
            name='packet_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='payload',
            field=models.TextField(null=True),
        ),
    ]
