# Generated by Django 4.1 on 2022-08-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0008_rename_ip_packet_ip_version_packet_packet_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
