# Generated by Django 4.1 on 2022-08-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0009_packet_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='dst_port',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='src_port',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
