# Generated by Django 4.1 on 2022-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0011_pcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pcap',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
