# Generated by Django 4.1 on 2022-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0012_packet_name_alter_pcap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
