# Generated by Django 4.1 on 2022-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0013_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_dir', models.CharField(max_length=255, null=True)),
                ('show_unknown_protocols', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
        ),
    ]
