# Generated by Django 4.1 on 2022-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0016_default_output_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='is_dst_private',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='is_src_private',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='port',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='output_dir',
            field=models.FilePathField(allow_files=False, allow_folders=True, null=True, path='/media/edwin/Projects/For Clients/pcap/static', recursive=True),
        ),
    ]
