# Generated by Django 4.1 on 2022-09-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0017_packet_is_dst_private_packet_is_src_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='port_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
