# Generated by Django 4.1 on 2022-09-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0020_default_update_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Dark'), (1, 'Light')], default=0),
        ),
    ]
