# Generated by Django 4.1 on 2022-09-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0021_default_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='skip_old_report',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
